/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface QrReader {
    'color': string;
  }
  interface QrReaderAttributes extends StencilHTMLAttributes {
    'color'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'QrReader': Components.QrReader;
  }

  interface StencilIntrinsicElements {
    'qr-reader': Components.QrReaderAttributes;
  }


  interface HTMLQrReaderElement extends Components.QrReader, HTMLStencilElement {}
  var HTMLQrReaderElement: {
    prototype: HTMLQrReaderElement;
    new (): HTMLQrReaderElement;
  };

  interface HTMLElementTagNameMap {
    'qr-reader': HTMLQrReaderElement
  }

  interface ElementTagNameMap {
    'qr-reader': HTMLQrReaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
